[package]
publish = false
name = "text-correction-utils-rs"
version = "0.1.4"
edition = "2021"

[package.metadata.maturin]
name = "text_correction_utils._internal"

[lib]
name = "text_correction_utils"
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4"
env_logger = "0.10"
rayon = "1.6"
indicatif = { version = "0.17", features = ["rayon"] }
pyo3 = { version = "0.18", features = ["anyhow", "extension-module", "abi3-py38", "auto-initialize", "macros"] }
itertools = "0.10"
rand = "0.8"
rand_distr = "0.4"
rand_chacha = "0.3"
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
serde_json = "1.0"
unicode-segmentation = "1.10"
unicode-normalization = "0.1"
num = "0.4"
anyhow = "1.0"
num_cpus = "1.14"
bitvec = "1"
numpy = "0.18"
pprof = "0.11"
clap = {version = "4", features = ["derive"]}

[dev-dependencies]
criterion = "0.4"

[features]
benchmark-utils = []

[profile.release]
lto = true
codegen-units = 1
strip = true
# debug = true

[[bench]]
required-features = ["benchmark-utils"]
name = "benchmark"
harness = false
