name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  fmt_rust:
    name: Check Rust formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  test_rust:
    name: Run Rust tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: cargo test

  test_python:
    name: Run Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"
      - uses: dtolnay/rust-toolchain@stable
      - name: Build
        uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          command: develop
          args: -E test
      - run: pytest -W ignore 
      
