name: Test, build and potentially release to PyPI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: dtolnay/rust-toolchain@stable
      - name: "Rust: Check and test"
        run: |
          cargo fmt --all -- --check
          cargo check
          cargo clippy -- -D warnings
          cargo test
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          args: --release --out dist
      - name: "Python: Install wheels and test"
        run: |
          pip install patchelf
          pip install dist/*.whl --force-reinstall
          pip install pytest
          python -m pytest -W ignore -v
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [linux]
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Publish release to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing *

