name: Build and test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: System dependencies
        run: |
          sudo apt install openssl -y
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: dtolnay/rust-toolchain@stable
      - name: "Rust: Check and test"
        run: |
          cargo fmt --all -- --check
          cargo check
          cargo clippy -- -D warnings
          cargo test
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          manylinux: auto
          args: --release --out dist
      - name: "Python: Install wheels and test import"
        run: |
          pip install patchelf
          pip install dist/*.whl --force-reinstall
          python -c "import text_correction_utils"
          # pip install pytest
          # python -m pytest -W ignore -v
