name: Upload release to PyPi

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-22.04

    steps:
    - uses: dtolnay/rust-toolchain@stable
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: v0.13.7
        manylinux: 2014/2_17
        command: publish
        args: --release --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
