name: Build and upload release to PyPi

on:
  release:
    types: [created]

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: PyO3/maturin-action@v1
        with:
          maturin-version: v0.13.7
          manylinux: auto
          command: publish
          args: --release --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}
